### ISSUE TITLE
how to test the acc on own data

### ISSUE THREAD

**Issue by ZziTaiLeo** [exitudio/GaitMixer#4]
Thank you for your outstanding work!I wanted to test the results with my own recorded data,  but could not find a demo.

**Comment by exitudio** [comment]
We don't have a custom dataset. But you can easily replace with you own dataset [here](https://github.com/exitudio/GaitMixer/blob/main/src/train.py#L107-L132)

**Comment by ZziTaiLeo** [comment]
> We don't have a custom dataset. But you can easily replace with you own dataset [here](https://github.com/exitudio/GaitMixer/blob/main/src/train.py#L107-L132)

However, this seems to require training? And I would like to take advantage of the Gaitmixer model you provided and test it with my own recorded video data.

**Comment by exitudio** [comment]
You can remove the training pipeline and call [evaluation function](https://github.com/exitudio/GaitMixer/blob/main/src/train.py#L218) directly.

**Comment by ZziTaiLeo** [comment]
> You can remove the training pipeline and call [evaluation function](https://github.com/exitudio/GaitMixer/blob/main/src/train.py#L218) directly.

tks! i will try it.
